#! /bin/sh

picom -f -D 5 -b

sxhkd &

# I have done this modularly, so I can decouple the monitor setup from the
# more generic bspwm setup

/home/sam/.config/bspwm/monitor.sh
/home/sam/.config/bspwm/window_setup.sh
